#!/usr/bin/env python3
"""
TSA_ch8_foundation_comparison
=============================
Classical vs Foundation model comparison chart for EUR/RON.

This chart is generated by the main EUR/RON foundation script:
    python generate_ch8_eurron_foundation.py

Output: charts/ch8_foundation_comparison.pdf

Author: Daniel Traian Pele
"""
# See TSA_ch8_eurron_foundation for the complete script.
# Run from repository root: python generate_ch8_eurron_foundation.py
